#
# Travis CI Build/Test Configuration
#
language: c
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install gcc-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
  - sudo apt-get install libacl1-dev
script: ./build.sh
